# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "pipeline_build"]
  pull_request:
    branches: [ "main", "pipeline_build"]
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest boto3 numpy matplotlib seaborn pandas scikit-metrics pickle5
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: python build
      run: |
        python main.py    
    - run: ls ${{ github.workspace }}

    - name: Set up AWS credentials from OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::430238166084:role/chetan_oidc_aws_github
        role-session-name: GitHubActions
        aws-region: us-east-1  # Specify your AWS region

    - name: Example AWS CLI command
      run: aws sagemaker list-clusters
            
    #- name: Test with pytest
     # run: |
      #  pytest
